##service properties
nameSpace=currentAccount
servicePort=6042
serviceName=ms-current-account
pathRelativeFileOrFolderProcess=/Users/camilaoregon/Documents/GitHub/test/baas-services-estructura/src/test/java/integration